// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTL-4JWgUpOkFMuqYPNPwqce9ATPqW7U',
    appId: '1:929898668919:web:2a933b0b2112263c983772',
    messagingSenderId: '929898668919',
    projectId: 'test-7e1a5',
    authDomain: 'test-7e1a5.firebaseapp.com',
    storageBucket: 'test-7e1a5.firebasestorage.app',
    measurementId: 'G-VCP8NLM78K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2iydUpW2eiZSfl8PzMbknOuoitAG7tnQ',
    appId: '1:929898668919:android:75bb025ab8e0742a983772',
    messagingSenderId: '929898668919',
    projectId: 'test-7e1a5',
    storageBucket: 'test-7e1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlk24vaflLND73oeZ47CoSho7FvrRRsk',
    appId: '1:929898668919:ios:0f3aebf62c043e79983772',
    messagingSenderId: '929898668919',
    projectId: 'test-7e1a5',
    storageBucket: 'test-7e1a5.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHlk24vaflLND73oeZ47CoSho7FvrRRsk',
    appId: '1:929898668919:ios:0f3aebf62c043e79983772',
    messagingSenderId: '929898668919',
    projectId: 'test-7e1a5',
    storageBucket: 'test-7e1a5.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuTL-4JWgUpOkFMuqYPNPwqce9ATPqW7U',
    appId: '1:929898668919:web:404b0cb44b4bec9a983772',
    messagingSenderId: '929898668919',
    projectId: 'test-7e1a5',
    authDomain: 'test-7e1a5.firebaseapp.com',
    storageBucket: 'test-7e1a5.firebasestorage.app',
    measurementId: 'G-X1PY7759S9',
  );

}