// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1M7Z4gKr884af185ykRRBm9Tu7uiBtrA',
    appId: '1:431342837775:web:a525d8e9644aa939ae437a',
    messagingSenderId: '431342837775',
    projectId: 'chess-pro-app',
    authDomain: 'chess-pro-app.firebaseapp.com',
    storageBucket: 'chess-pro-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlL6dIiSZt-t1q1qFDBgQC_DuZalhwoOs',
    appId: '1:431342837775:android:7c2d46794623defcae437a',
    messagingSenderId: '431342837775',
    projectId: 'chess-pro-app',
    storageBucket: 'chess-pro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTL1H4OI5xSBFprpvjeGXSsoId7wv5rGA',
    appId: '1:431342837775:ios:886a69ee28b06c02ae437a',
    messagingSenderId: '431342837775',
    projectId: 'chess-pro-app',
    storageBucket: 'chess-pro-app.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTL1H4OI5xSBFprpvjeGXSsoId7wv5rGA',
    appId: '1:431342837775:ios:886a69ee28b06c02ae437a',
    messagingSenderId: '431342837775',
    projectId: 'chess-pro-app',
    storageBucket: 'chess-pro-app.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1M7Z4gKr884af185ykRRBm9Tu7uiBtrA',
    appId: '1:431342837775:web:f7aa8d3e70a51d34ae437a',
    messagingSenderId: '431342837775',
    projectId: 'chess-pro-app',
    authDomain: 'chess-pro-app.firebaseapp.com',
    storageBucket: 'chess-pro-app.firebasestorage.app',
  );

}